Areas/Consign/Pages/Components/Default/DefaultViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace th.onlineconsign.Components
{
    public class DefaultViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string viewName)
        {
            // The default View "Default" is not used here for business structure information.
            return await Task<IViewComponentResult>.Run(() =>
            {
                // Get the name of the view according to the name of sampleuc
                return View(viewName);
            });
        }
    }
}

Areas/Consign/Pages/Components/GangJin/GangJinViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using th.onlineconsign.ExtViewModels;
using th.onlineconsign.Model;
using th.onlineconsign.Services;

namespace th.onlineconsign.Components
{
    public class GangJinViewComponent : ViewComponent
    {
        ItemDbContext db;
        ISampleUcControler sampleUcControler;

        public SampleStorageAddonGangJinExt SampleStorageAddonGangJinExt { get; set; } = new SampleStorageAddonGangJinExt();

        public GangJinViewComponent(ItemDbContext db, ISampleUcControler service1)
        {
            this.db = db;
            sampleUcControler = service1;
        }

        public async Task<IViewComponentResult> InvokeAsync(string viewName, string sampleId)
        {
            return await Task<IViewComponentResult>.Run(() =>
            {
                return View(viewName, SampleStorageAddonGangJinExt);
            });
        }
    }

    
}

Areas/Consign/Pages/Components/ShuiNi/ShuiNiViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace th.onlineconsign.Components
{
    public class ShuiNiViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string viewName)
        {

            // The default View "Default" is not used here for business structure information.
            return await Task<IViewComponentResult>.Run(() =>
            {
                // Get the name of the view according to the name of sampleuc
                return View(viewName);
            });
        }
    }
}

Areas/Consign/Pages/Item.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using th.onlineconsign.Model;

public class ItemPageModel : PageModel
{
    private readonly ItemDbContext db;
    public ItemPageModel(ItemDbContext db)
    {
        this.db = db;
    }

    public List<ItemItem> Items { get; set; }

    public string KindName { get; set; }

    [BindProperty]
    public string KindId { get; set; }

    [BindProperty]
    public string SearchKey { get; set; }

    public async Task OnGetAsync()
    {
        if (KindId == null)
            KindId = RouteData.Values["handler"].ToString();

        await InitPage(KindId);
    }

    public async Task OnPostSearchItem()
    {
        await InitPage(KindId);
    }

    public async Task InitPage(string kindId)
    {
        // get kindname
        KindName = await db.ItemKind
        .Where(x => x.KindId.ToString() == kindId)
        .Select(x => x.KindName).FirstAsync();

        // get items
        Items = await db.ItemItem
        .Where(x => x.CanConsign == 1
            && x.KindId.ToString() == kindId
            && (SearchKey != null ? x.ItemName.Contains(SearchKey) : true))
        .Select(x => new ItemItem
        {
            ItemId = x.ItemId,
            ItemName = x.ItemName,
            ItemDescription = x.ItemDescription
        })
        .OrderBy(x => x.ItemId).ToListAsync();
    }
}

Areas/Consign/Pages/Kind.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using th.onlineconsign.Model;

public class KindPageModel : PageModel
{
    private readonly ItemDbContext db;
    public KindPageModel(ItemDbContext db)
    {
        this.db = db;
    }

    public List<ItemKind> Kinds { get; set; }

    public async Task OnGetAsync()
    {
        Kinds = await db.ItemKind
        .Where(x => x.CanConsign == 1)
        .Select(x => new ItemKind
        {
            KindId = x.KindId,
            KindName = x.KindName,
            KindDescription = x.KindDescription
        })
        .OrderBy(x => x.KindId).ToListAsync();
    }
}

Areas/Consign/Pages/Sample.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using th.onlineconsign.Model;

public class SamplePageModel : PageModel
{
    ItemDbContext db;
    public SamplePageModel(ItemDbContext db)
    {
        this.db = db;
    }

    public string KindName { get; set; }
    public string ItemName { get; set; }

    public List<ItemSample> Samples { get; set; }

    [BindProperty]
    public string SearchKey { get; set; }

    [BindProperty(SupportsGet = true)]
    public string ItemId { get; set; }

    public async Task OnGetAsync()
    {
        ItemId = RouteData.Values["handler"].ToString();

        var tuple = await InitPage(ItemId, null);
        KindName = tuple.Item1;
        ItemName = tuple.Item2;
        Samples = tuple.Item3;
    }

    public async Task OnPostSearchSampleAsync()
    {
        var tuple = await InitPage(ItemId, SearchKey);
        KindName = tuple.Item1;
        ItemName = tuple.Item2;
        Samples = tuple.Item3;
    }

    private async Task<Tuple<string, string, List<ItemSample>>> InitPage(string itemId, string searchkey)
    {
        // get kindname for breadcrumb
        var kingName = await db.ItemKind
            .Where(x => x.KindId.ToString() == itemId.Substring(0, 2))
            .Select(x => x.KindName).FirstAsync();

        // get itemname for breadcrumb
        var itemName = await db.ItemItem
            .Where(X => X.ItemId.ToString() == itemId)
            .Select(x => x.ItemName).FirstAsync();

        // get samples by itemid
        var samples = await db.ItemSample
            .Where(
                x => x.CanConsign == 1
                && x.ItemId.ToString() == itemId
                && (searchkey != null ? x.SampleName.Contains(searchkey) ||
                    x.SampleJudge.Contains(searchkey) : true))
            .Select(x => new ItemSample()
            {
                SampleId = x.SampleId,
                SampleName = x.SampleName,
                SampleJudge = x.SampleJudge
            })
            .OrderBy(x => x.SampleId).ToListAsync();

        return new Tuple<string, string, List<ItemSample>>(kingName, itemName, samples);
    }
}

Areas/Consign/Pages/SampleDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using th.onlineconsign.ExtViewModels;
using th.onlineconsign.Model;
using th.onlineconsign.Services;
using static BasePageModelForConsign;

public partial class SampleDetailsPageModel : BasePageModelForConsign
{
    ISampleConsignService sampleConsignService;
    SampleStorageDbContext dbSampleStorage;
    ISampleUcControler sampleUcControler;
    ITools tools;

    public SampleDetailsPageModel(ISampleConsignService service3, SampleStorageDbContext db2, ISampleUcControler service1, ITools service2)
    {
        sampleConsignService = service3;
        dbSampleStorage = db2;
        sampleUcControler = service1;
        tools = service2;
    }

    [BindProperty]
    public SampleStorageMainExt SampleStorageExt { get; set; } = new SampleStorageMainExt();

    public SampleDetailsPageCtl SampleDetailsPageCtl { get; set; } = new SampleDetailsPageCtl();

    public SelectList Specs { get; set; }

    public SelectList Grades { get; set; }

    public SelectList DelegateQuanUnit { get; set; }

    public async Task OnGetAsync()
    {
        SampleStorageExt.SampleId = int.Parse(RouteData.Values["handler"].ToString());

        var tuple = await sampleConsignService.GetInitDataForSampleDetailPage(SampleStorageExt.SampleId.ToString(), null);
        SampleStorageExt.KindName = tuple.Item1;
        SampleStorageExt.ItemName = tuple.Item2;
        SampleStorageExt.SampleName = tuple.Item3;
        SampleStorageExt.Parameters = tuple.Item6.Select(x => tools.EntityCopy<ItemParameter, ItemParameterExt>(x)).ToList();
        Specs = new SelectList(tuple.Item4, nameof(ItemSpec.SpecId), nameof(ItemSpec.SpecName), null, null);
        Grades = new SelectList(tuple.Item5, nameof(ItemGrade.GradeId), nameof(ItemGrade.GradeName), null, null);
        DelegateQuanUnit = new SelectList(tuple.Rest.Item1, nameof(DpDelegateQuanUnit.Nam), nameof(DpDelegateQuanUnit.Nam), null, null);
        var sampleUcName = tuple.Rest.Item2;

        var sampleucinfo = sampleUcControler.GetSampleUcViewComponentInfo(sampleUcName, SampleStorageExt.SampleId.ToString());
        SampleStorageExt.SampleUcDbTableName = sampleucinfo.Item1;// the same as sampleuc table name
        SampleStorageExt.SampleUcViewComponentViewName = sampleucinfo.Item2;

        SampleDetailsPageCtl.IfShouldAddScript = sampleUcControler.GetIfShouldAddScript(sampleUcName, SampleStorageExt.SampleId.ToString());
        SampleDetailsPageCtl.ShowSpecManual = Specs.Count() <= 0 ? ShowHideCssClass.show : ShowHideCssClass.hide;
        SampleDetailsPageCtl.ShowSpecSelect = Specs.Count() <= 0 ? ShowHideCssClass.hide : ShowHideCssClass.show;
        SampleDetailsPageCtl.ShowGradeManual = Grades.Count() <= 0 ? ShowHideCssClass.show : ShowHideCssClass.hide;
        SampleDetailsPageCtl.ShowGradeSelect = Grades.Count() <= 0 ? ShowHideCssClass.hide : ShowHideCssClass.show;
        SampleDetailsPageCtl.ShowProductorManual = tuple.Item7 ? ShowHideCssClass.show : ShowHideCssClass.hide;
        SampleDetailsPageCtl.ShowProductorSelect = tuple.Item7 ? ShowHideCssClass.hide : ShowHideCssClass.show;
        SampleDetailsPageCtl.ReadonlyProductorManual = tuple.Item7 ? ReadonlyCssClass.na : ReadonlyCssClass.ReadOnly;
    }

    public async Task<JsonResult> OnGetSearchProductor(string sampleId, string searchkey)
    {
        return new JsonResult(await sampleConsignService.GetSearchProductor(sampleId, searchkey));
    }

    public async Task<RedirectToPageResult> OnPostSave()
    {
        var parmIds = string.Empty;
        var parmNames = string.Empty;
        SampleStorageExt.Parameters.ForEach((x) =>
        {
            if (x.Checked)
            {
                parmIds += $"{x.ParameterId};";
                parmNames += $"{x.ParameterName};";
            }
        });
        var sampleNo = await sampleConsignService.GetNewSampleConsignId();

        var sampleStorageMain = tools.EntityCopyForParent<SampleStorageMainExt, SampleStorageMain>(SampleStorageExt);
        sampleStorageMain.ContractSignNumber = string.Empty;
        sampleStorageMain.JzcertificateNo = string.Empty;
        sampleStorageMain.QycertificateNo = string.Empty;

        sampleStorageMain.OperatorUserId = Guid.Empty;
        sampleStorageMain.MoldingDate = DateTime.Parse("1753-01-01 00:00:00.000");
        sampleStorageMain.AgeTime = -1;

        sampleStorageMain.Id = Guid.NewGuid();
        sampleStorageMain.SampleNo = sampleNo;
        sampleStorageMain.DetectonDate = DateTime.Now;
        sampleStorageMain.KindId = int.Parse(sampleStorageMain.SampleId.ToString().Substring(0, 2));
        sampleStorageMain.ItemId = int.Parse(sampleStorageMain.SampleId.ToString().Substring(0, 4));

        sampleStorageMain.ExamParameter = parmIds;
        sampleStorageMain.CreateDateTime = DateTime.Now;
        sampleStorageMain.LastEditDateTime = DateTime.Now;

        sampleStorageMain.ExamParameterCn = parmNames;
        await dbSampleStorage.SampleStorageMain.AddAsync(sampleStorageMain);

        MethodInfo methodInfo = GetType().GetMethod($"{sampleStorageMain.SampleUcDbTableName}_AddonSave");
        if (methodInfo != null)
        {
            await Task.Run(() =>
            {
                methodInfo.Invoke(this, new object[] { sampleStorageMain.Id });
            });

            var ir = await dbSampleStorage.SaveChangesAsync();

        }
        return RedirectToPage(pageName: "SampleDetails", routeValues: new { handler = sampleStorageMain.SampleId, area = "Consign" });
    }
}
public class SampleDetailsPageCtl
{
    public ShowHideCssClass ShowSpecManual { get; set; }

    public ShowHideCssClass ShowSpecSelect { get; set; }

    public ShowHideCssClass ShowGradeManual { get; set; }

    public ShowHideCssClass ShowGradeSelect { get; set; }

    public ShowHideCssClass ShowProductorManual { get; set; }

    public ShowHideCssClass ShowProductorSelect { get; set; }

    public ReadonlyCssClass ReadonlyProductorManual { get; set; }

    public bool IfShouldAddScript { get; set; }
}

Areas/Consign/Pages/Item.cshtml
@page "{handler}"
@model ItemPageModel
@{}

@{
    ViewData["Title"] = "项目";
}
@section Stylesheet{
    <link rel="stylesheet" href="~/css/lar.th.css" />
}

@section Breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb lar-breadcrumb">
            <li class="breadcrumb-item"><a asp-page="/Index" asp-area="">首页</a></li>
            <li class="breadcrumb-item"><a asp-page="/Kind" asp-page-handler="-1" asp-area="consign">大类</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.KindName</li>
        </ol>
    </nav>
}

<div class="row mb-4">
    <div class="col-3 mt-2"><h6>项目种类<span class="badge badge-secondary ml-2">@(Model.Items==null?0:Model.Items.Count())</span></h6></div>
    <div class="col-4"></div>
    <div class="col-5">
        <form method="post" asp-page-handler="searchitem">
            <div class="input-group input-group-sm">
                <input type="text" class="form-control w-25" placeholder="项目名称" aria-label="项目名称" 
                aria-describedby="button-addon2" asp-for="SearchKey">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><span class="fas fa-search"></button>
                </div>
            </div>
            <input type="hidden" asp-for="KindId">
        </form>
    </div>
</div>

<div class="card-columns pt-2 border-top lar">
@if(Model.Items != null)
{
    @foreach (var item in Model.Items)
    {
        <div class="card border-secondary text-center">
            <a class="lar-a" asp-page="/Sample" asp-page-handler="@item.ItemId" asp-area="Consign">
            <div class="card-body">
                <h5 class="card-title">@item.ItemName</h5>
                <p class="card-text">@item.ItemDescription</p>
            </div>
            </a>
            <div class="card-footer"><small class="text-muted">--</small></div>
        </div>
    }
}
</div>

Areas/Consign/Pages/Kind.cshtml
@page "{handler}"
@model KindPageModel
@{
    ViewData["Title"] = "大类";
}
@section Stylesheet{
    <link rel="stylesheet" href="~/css/lar.th.css" />
}

@section Breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb lar-breadcrumb">
            <li class="breadcrumb-item"><a asp-page="/Index" asp-area="">首页</a></li>
            <li class="breadcrumb-item active" aria-current="page">大类</li>
        </ol>
    </nav>
}
<div class="card-columns lar">
@foreach (var kind in Model.Kinds)
{
    var commonly = (new int[] { 11, 13 }).Any(x => x == kind.KindId);
    <div class="card border-secondary text-center">
        <a class="lar-a" asp-page="/Item" asp-page-handler="@kind.KindId" asp-area="Consign">
        <div class="card-body @if(commonly){@("bg-secondary text-white")}">
            <h5 class="card-title">@kind.KindName</h5>
            <p class="card-text">@kind.KindDescription</p>
        </div>
        </a>
        <div class="card-footer"><small class="text-muted">最后收样 3 mins ago</small></div>
    </div>
}
</div>

Areas/Consign/Pages/Sample.cshtml
@page "{handler}"
@model SamplePageModel
@{
    ViewData["Title"] = "样品";
}
@section Stylesheet{
    <link rel="stylesheet" href="~/css/lar.th.css" />
}

@section Breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb lar-breadcrumb">
            <li class="breadcrumb-item"><a asp-page="/Index" asp-area="">首页</a></li>
            <li class="breadcrumb-item"><a asp-page="/Kind" asp-page-handler="-1" asp-area="consign">大类</a></li>
            <li class="breadcrumb-item"><a asp-page="/Item" asp-page-handler="@Model.ItemId.Substring(0, 2)" asp-area="consign">@Model.KindName</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.ItemName</li>
        </ol>
    </nav>
}

<div class="row mb-4">
    <div class="col-3 mt-2"><h6>样品种类<span class="badge badge-secondary ml-2">@(Model.Samples==null?0:Model.Samples.Count())</span></h6></div>
    <div class="col-4"></div>
    <div class="col-5">
        <form method="post" asp-page-handler="searchsample">
            <div class="input-group input-group-sm">
                <input type="text" class="form-control" placeholder="样品名称" aria-label="样品名称" 
                aria-describedby="button-addon2" asp-for="SearchKey">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><span class="fas fa-search"></button>
                </div>
            </div>
            <input type="hidden" asp-for="ItemId">
        </form>
    </div>
</div>

<div class="card-columns pt-2 border-top lar">
@if(Model.Samples != null)
{
    @foreach (var sample in Model.Samples)
    {
        <div class="card border-secondary text-center">
            <a class="lar-a" asp-page="/SampleDetails" asp-page-handler="@sample.SampleId" asp-area="Consign">
            <div class="card-body">
                <h5 class="card-title">@sample.SampleName</h5>
                <p class="card-text">@sample.SampleJudge</p>
            </div>
            </a>
            <div class="card-footer"><small class="text-muted">--</small></div>
        </div>
    }
}
</div>

Areas/Consign/Pages/SampleDetails.cshtml
@page "{handler}"
@model SampleDetailsPageModel
@{
    ViewData["Title"] = "样品详细信息";
}
@section Stylesheet{
    <link rel="stylesheet" href="~/css/lar.th.css" />
}
@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/js/sampledetails.cshtml.js" asp-append-version="true"></script>
}
@section Scripts_SampleUc{
    @if(Model.SampleDetailsPageCtl.IfShouldAddScript)
    {
        <script src="~/js/vc-@(Model.SampleStorageExt.SampleUcViewComponentViewName.ToLower()).cshtml.js" asp-append-version="true"></script>
    }
}
@section Breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb lar-breadcrumb">
            <li class="breadcrumb-item"><a asp-page="/Index" asp-area="">首页</a></li>
            <li class="breadcrumb-item"><a asp-page="/Kind" asp-page-handler="-1" asp-area="consign">大类</a></li>
            <li class="breadcrumb-item"><a asp-page="/Item" asp-page-handler="@Model.SampleStorageExt.SampleId.ToString().Substring(0, 2)" asp-area="consign">@Model.SampleStorageExt.KindName</a></li>
            <li class="breadcrumb-item"><a asp-page="/Sample" asp-page-handler="@Model.SampleStorageExt.SampleId.ToString().Substring(0, 4)" asp-area="consign">@Model.SampleStorageExt.ItemName</a></li>
            <li class="breadcrumb-item active font-weight-bold" aria-current="page">@Model.SampleStorageExt.SampleName</li>
        </ol>
    </nav>
}

<form method="post">
<div>
    <div class="form-row">
        <div class="col-6">
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" asp-for="SampleStorageExt.SpecId">规格</label>
                </div>
                <select class="custom-select custom-select-sm @Model.SampleDetailsPageCtl.ShowSpecSelect" id="SampleStorageExt_SpecId" name="SampleStorageExt.SpecId" asp-items="Model.Specs">
                    <option selected>请选择...</option>
                </select>
                <input type="text" class="form-control @Model.SampleDetailsPageCtl.ShowSpecManual" id="SampleStorageExt_SpecName" name="SampleStorageExt.SpecName" placeholder="请输入" aria-label="规格">
            </div>
        </div>
        <div class="col-6">
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" asp-for="SampleStorageExt.GradeId">强度/等级</label>
                </div>
                <select class="custom-select custom-select-sm @Model.SampleDetailsPageCtl.ShowGradeSelect" id="SampleStorageExt_GradeId" name="SampleStorageExt.GradeId" asp-items="Model.Grades">
                    <option selected>请选择...</option>
                </select>
                <input type="text" class="form-control @Model.SampleDetailsPageCtl.ShowGradeManual" id="SampleStorageExt_GradeName" name="SampleStorageExt.GradeName" placeholder="请输入" aria-label="强度/等级">
            </div>
        </div>
    </div>
    <div class="form-row mb-3">
        <div class="col-12">
            <div class="rounded list-frame-title">检测参数</div>
            <div class="border rounded scroll-checkbox-list-h100">  
                @foreach (var parm in Model.SampleStorageExt.Parameters)
                {
                <div class="custom-control custom-checkbox custom-control-inline">
                    <input type="checkbox" class="custom-control-input" id="chkparm_@parm.ParameterId" name="SampleStorageExt.Parameters[@parm.ParameterId].Checked" 
                        value="true" @if(parm.IsDefault.Value){@("Checked")}>
                    <label class="custom-control-label" for="chkparm_@parm.ParameterId">@parm.ParameterName</label>
                    <input type="hidden" name="SampleStorageExt.Parameters[@parm.ParameterId].ParameterName" value="@parm.ParameterName" />
                    <input type="hidden" name="SampleStorageExt.Parameters[@parm.ParameterId].ParameterId" value="@parm.ParameterId" />
                    <input type="hidden" name="SampleStorageExt.Parameters.Index" value="@parm.ParameterId" />
                </div>
                }
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-12">
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" asp-for="SampleStorageExt.RecordCertificate">备案证及生产厂家</label>
                </div>

                <input type="text" class="form-control @Model.SampleDetailsPageCtl.ShowProductorSelect" id="searchProductorSearchKey" placeholder="关键字" aria-label="关键字">

                <div class="input-group-prepend @Model.SampleDetailsPageCtl.ShowProductorSelect">
                    <button class="btn btn-outline-secondary" id="searchProductor" type="button">搜索</button>
                </div>

                <select class="custom-select custom-select-sm @Model.SampleDetailsPageCtl.ShowProductorSelect" id="SampleStorageExt_RecordCertificate">
                    <option value="" selected>请选择...</option>
                </select>
                <input type="hidden" id="SampleStorageExt_RecordCertificateHidden" name="SampleStorageExt.RecordCertificate">
                <input type="text" class="form-control w-30" id="produceFactory" name="SampleStorageExt.ProduceFactory"
                    placeholder="生产厂家名称" aria-label="生产厂家" @Model.SampleDetailsPageCtl.ReadonlyProductorManual>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-6">
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" asp-for="SampleStorageExt.DelegateQuan">代表数量</label>
                </div>
                <input type="number" min="0" class="form-control" id="SampleStorageExt_DelegateQuan" name="SampleStorageExt.DelegateQuan" placeholder="请输入" aria-label="代表数量">
                <select class="custom-select custom-select-sm" id="SampleStorageExt_DelegateQuanUnit" name="SampleStorageExt.DelegateQuanUnit" asp-items="Model.DelegateQuanUnit">
                    <option value="0" selected>请选择...</option>
                </select>
            </div>
        </div>
        <div class="col-6">
            <div class="input-group input-group-sm mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" asp-for="SampleStorageExt.ProJectPart">使用部位</label>
                </div>
                <input type="text" class="form-control" id="SampleStorageExt_ProJectPart" name="SampleStorageExt.ProJectPart" value="@Model.SampleStorageExt.ProJectPart" placeholder="请输入" aria-label="使用部位">
            </div>
        </div>
    </div>
    @await Component.InvokeAsync(Model.SampleStorageExt.SampleUcDbTableName, 
        new {ViewName=Model.SampleStorageExt.SampleUcViewComponentViewName, SampleId=Model.SampleStorageExt.SampleId.ToString()})
    <div>
        <button class="btn btn-primary" asp-route-handler="save">保存</button>
    </div>
</div>
<input id="hiddenSampleId" name="SampleStorageExt.SampleId" type="hidden" value="@Model.SampleStorageExt.SampleId">
<input name="SampleStorageExt.KindName" type="hidden" value="@Model.SampleStorageExt.KindName">
<input name="SampleStorageExt.ItemName" type="hidden" value="@Model.SampleStorageExt.ItemName">
<input name="SampleStorageExt.SampleName" type="hidden" value="@Model.SampleStorageExt.SampleName">
<input name="SampleStorageExt.SampleUcDbTableName" type="hidden" value="@Model.SampleStorageExt.SampleUcDbTableName">
</form>